version: '3'
services:
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:latest
    ports:
      - "4442:4442"
      - "4443:4443"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
    networks:
      - grid

  selenium-node-chrome1:
    container_name: selenium-node-chrome1
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_MAX_INSTANCES=3
      - GRID_MAX_SESSION=3
      - GRID_BROWSER_TIMEOUT=3000
      - GRID_TIMEOUT=3000
    shm_size: "4g"
    networks:
      - grid

  selenium-node-chrome2:
    container_name: selenium-node-chrome2
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_MAX_INSTANCES=3
      - GRID_MAX_SESSION=3
      - GRID_BROWSER_TIMEOUT=3000
      - GRID_TIMEOUT=3000
    shm_size: "4g"
    networks:
      - grid
      
  selenium-node-chrome3:
    container_name: selenium-node-chrome3
    image: selenium/node-chrome:latest
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_MAX_INSTANCES=3
      - GRID_MAX_SESSION=3
      - GRID_BROWSER_TIMEOUT=3000
      - GRID_TIMEOUT=3000
    shm_size: "4g"
    networks:
      - grid
  voupra_container:
    container_name: voupra_container
    build:
      context: .
      dockerfile: Dockerfile.3
    depends_on:
      - selenium-hub
    networks:
      - grid

  vmz_container:
    container_name: vmz_container
    build:
      context: .
      dockerfile: Dockerfile.2
    depends_on:
      - selenium-hub
    networks:
      - grid

  ml_container:
    container_name: ml_container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium-hub
    networks:
      - grid
networks:
  grid:
    external: true
