version: '3'
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - mynetwork  
  python_app:
    container_name: python_app
    build:
      context: .
      dockerfile: Dockerfile.python_selenium
    depends_on:
      - selenium
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge      